services:
  postgres:
    image: postgres:18
    container_name: commng-postgres
    restart: unless-stopped
    env_file:
      - server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: America/New_York
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg-data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: commng-redis
    restart: unless-stopped
    command: redis-server # --requirepass ${REDIS_PASSWORD}
    env_file:
      - server/.env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  redis-data: